name: 02-1 Staging - Docker-Ghcr

on:
  workflow_call:
    inputs:
      docker-mode:
        description: 'Docker build mode (canary or release)'
        required: false
        type: string
        default: ""

env:
  REGISTRY: ghcr.io
  USERNAME: ${{ github.actor }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Display_data:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Docker registry: ${{ env.REGISTRY }}"
          echo "Docker image name: ${{ env.IMAGE_NAME }}"
          echo "Docker username: ${{ env.USERNAME }}"
          echo "Docker mode: ${{ inputs.docker-mode }}"

  Build_and_push_Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Downcase Image Name
        run: echo "IMAGE_NAME_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Back build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}-backend:latest
      
      - name: Front build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}-frontend:latest
          build-args: MODE=:canary